import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "../components/navbar";
import { NextAuthProvider } from "./Providers";
import { RProviders } from "./RProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <RProviders>
            <Navbar />
            {children}
          </RProviders>
        </NextAuthProvider>
      </body>
    </html>
  );
}
